---
- name: Create storage directories for Lake
  hosts: minio_hosts
  gather_facts: false
  vars_files:
    - vars/lake_storage.yaml
  tasks:
    - name: Create storage directories
      when: not aws_deployment
      include_tasks: tasks/storage_dir_create.yaml

- name: Install components for Lake service
  hosts: server
  gather_facts: false
  environment:
    HELM_PLUGINS: '{{ helm_plugins_dir }}'
    KUBECONFIG: '{{ kubeconfig_yaml }}'
  vars_files:
    - vars/lake_storage.yaml
  tasks:
    - name: Set up storage
      when: not aws_deployment
      include_tasks: tasks/storage_setup.yaml

    - name: Set up EBS storage class
      when: aws_deployment
      include_tasks: tasks/ebs_storage_setup.yaml

    - name: Install MinIO
      # when: not aws_deployment
      include_tasks: services/minio.yaml

    - name: Install Hive Metastore Service (HMS)
      include_tasks: services/hive.yaml
