---
- name: Create storage directories for Postgres
  hosts: k3s_cluster
  gather_facts: false
  tasks:
    - name: Create storage directories
      when: not aws_deployment
      ansible.builtin.include_role:
        name: postgres
        tasks_from: storage

- name: Deploy Postgres
  when: not aws_deployment
  hosts: server
  gather_facts: false
  environment:
    KUBECONFIG: '{{ kubeconfig_yaml }}'
    K8S_AUTH_KUBECONFIG: '{{ kubeconfig_yaml }}'
  roles:
    - postgres

- name: Initialize RDS Postgres
  when: aws_deployment
  hosts: server
  gather_facts: false
  environment:
    KUBECONFIG: '{{ kubeconfig_yaml }}'
    K8S_AUTH_KUBECONFIG: '{{ kubeconfig_yaml }}'
  tasks: 
    - name: Include RDS init
      when: aws_deployment
      ansible.builtin.include_tasks: tasks/rds_init.yaml
    
