---
- name: Create storage directories for Postgres
  hosts: k3s_cluster
  gather_facts: false
  vars_files:
    - vars/postgres_storage.yaml
  tasks:
    - name: Create storage directories
      when: not aws_deployment
      include_tasks: tasks/storage_dir_create.yaml

- name: Install Postgres
  hosts: server
  gather_facts: false
  environment:
    HELM_PLUGINS: '{{ helm_plugins_dir }}'
    KUBECONFIG: '{{ kubeconfig_yaml }}'
  vars_files:
    - vars/postgres_storage.yaml
  vars:
    rds_init_ns: "{{ rds_init_namespace | default('default') }}"

  pre_tasks:
    - name: Initialize empty SQL statements list
      ansible.builtin.set_fact:
        postgres_init_sql: []

    - name: Add SQL statements from local templates
      ansible.builtin.set_fact:
        postgres_init_sql: '{{ postgres_init_sql + lookup("template", item) | from_yaml }}'
      when: module_enabled not in vars or vars[module_enabled] | bool
      vars:
        module_name: "{{ item | basename | regex_replace('_init_sql\\.yaml$', '') }}"
        module_enabled: "{{ module_name + '_enabled' }}"
      loop: "{{ lookup('fileglob', playbook_dir ~ '/templates/postgres_init/*_init_sql.yaml', wantlist=True) }}"
      loop_control:
        label: '{{ item | basename }}'
      delegate_to: localhost
      run_once: true

  tasks:
    - name: Inititalize RDS Postgres Instance
      when: aws_deployment
      include_tasks: tasks/rds_init.yaml

    - name: Set up cloudnative-pg Postgres cluster
      when: not aws_deployment
      include_tasks: services/cloudnative_pg.yaml