- name: Setup PostgreSQL database and user
  block:
    - name: Create user (ignore if exists)
      kubernetes.core.k8s_exec:
        namespace: '{{ postgres_cluster_namespace }}'
        pod: '{{ postgres_cluster_name }}-1'
        command: |
          psql --dbname=postgres -c "CREATE USER {{ open_webui_postgres_user }} WITH PASSWORD '{{ open_webui_postgres_password }}';"
      register: user_result
      failed_when:
        - user_result.rc != 0
        - '"already exists" not in user_result.stderr'