---
- |
    DO
    $$
    BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{{ postgres_user }}') THEN
        CREATE ROLE {{ postgres_user }} LOGIN PASSWORD '{{ postgres_password }}';
      ELSE
        ALTER ROLE {{ postgres_user }} WITH LOGIN PASSWORD '{{ postgres_password }}';
      END IF;
    END
    $$;
- "GRANT {{ postgres_user }} TO CURRENT_USER;"
- |
    SELECT 'CREATE DATABASE {{ingest_postgres_table_name}} OWNER {{ postgres_user }}'
    WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '{{ingest_postgres_table_name}}');
    \gexec
- "REVOKE {{ postgres_user }} FROM CURRENT_USER;"